### ISSUE TITLE
[Feature Reuqest] - Support the Minecraft Server

### ISSUE THREAD

**Issue by StoneMcYT** [Avdan-OS/Tinan#13]
Things to add:
a IP and dynmap command to grab the server IP and the dynmap URL - Should be configured in config.json
and adding a server status API support (https://api.mcsrvstat.us/) - Should be able to config in config .json

**Comment by MrSerge01** [comment]
Will do in my PR, my boss

**Comment by MrSerge01** [comment]
I don't know if it's still required to do...

**Comment by StoneMcYT** [comment]
yd now i can bench this i alr got a API that can do it and will write it in when its time

**Comment by MrSerge01** [comment]
pro, if you want include it in the draft pr of mine
