### ISSUE TITLE
[BUG] - Node ./src/index.js failure

### ISSUE THREAD

**Issue by StoneMcYT** [Avdan-OS/Tinan#18]
Running node ./src/index.js does not work and results in a  invalid token error

it requires me to
```
cd src
node .
```
Fix
Allow node ./src/index.js so that the bot can be run in the control panel which uses docker which depends on node ./src/index.js

**Comment by TechStudent10** [comment]
I don't understand the fix

**Comment by MrSerge01** [comment]
@TechStudent11 well the server errored 1 time because there was that 1 line that goes like `const commands = 'src/commands'` and the server thought that the path to the commands folder is `Tinan/src/src/commands` when there's only 1 src

**Comment by MrSerge01** [comment]
will be fixed in an upcoming pr of mine

**Comment by TechStudent10** [comment]
Alright.

**Comment by StoneMcYT** [comment]
> I don't understand the fix

I have no idea whats the fix thats thing 
I only know what you need to fix

**Comment by MrSerge01** [comment]
Fun fact: another PR fixed it before me. Closing now 😩
