### ISSUE TITLE
Tinan is offline 😭😭

### ISSUE THREAD

**Issue by dxvv-software** [Avdan-OS/Tinan#33]
noo @MrSerge01 fix plss

**Comment by MrSerge01** [comment]
this is not an issue i can fix bruh

**Comment by Froxcey** [comment]
This has to do with VPS and not Goos, and it will come back on when it wants to.

**Comment by MrSerge01** [comment]
Tinan is sentient.

**Comment by dxvv-software** [comment]
> Tinan is sentient.

WHAT

**Comment by MrSerge01** [comment]
> > Tinan is sentient.
> 
> WHAT

Yes.

**Comment by dxvv-software** [comment]
> > > Tinan is sentient.
> > 
> > 
> > WHAT
> 
> Yes.

### **y e s.**

**Comment by MrSerge01** [comment]
> > > > Tinan is sentient.
> > > 
> > > 
> > > WHAT
> > 
> > 
> > Yes.
> 
> ### **y e s.**

why the yes is so small?

# ***y          e          s          .***

**Comment by dxvv-software** [comment]
> > > > > Tinan is sentient.
> > > > 
> > > > 
> > > > WHAT
> > > 
> > > 
> > > Yes.
> > 
> > 
> > ### **y e s.**
> 
> why the yes is so small?
> 
> # _**y e s .**_
y                                                  e                                                  s

**Comment by dxvv-software** [comment]
# _**y e s**_
