### ISSUE TITLE
[Feature Request] - Create a Define command, which takes an argument and explains the argument's meaning

### ISSUE THREAD

**Issue by MarcTheDuck** [Avdan-OS/Tinan#34]
Would be using Oxford Languages API and would be used like <prefix>define <argument>

An API key can be retrieved from
https://developer.oxforddictionaries.com/

**Comment by Marc449b** [comment]
If this gets approved, I'd probably be able to implement it as well.

**Comment by StoneMcYT** [comment]
As this feature is not needed and will not come to any use I would close this as our bot developers and currently implementing other features
