### ISSUE TITLE
Problem in Readme:  line 57 of cmdHandler.js does not contain a string to replace

### ISSUE THREAD

**Issue by laughingsheep** [Avdan-OS/Tinan#8]
In step 9 of the readme it instructs to "open `cmdHandler.js` and in the 57th line, replace the number in a string with your ID", however line 57 **does not** contain a string to replace to and reads `message.delete()` instead.

**Comment by MrSerge01** [comment]
Hello! It will be fixed in my future pull request. Thanks for pointing out!

**Comment by MrSerge01** [comment]
#32 has the fix.
